services:
  - type: web
    name: mcq-extractor-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "1"
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
    autoDeploy: true
