services:
  - type: web
    name: mcq-extractor-ai
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

